if x>128 and x<room_width-128 ///fixe les bordures...
view_xview=lerp(view_xview,x-view_wview/2,acc) // camer lerp.... val1 xview, vale 2 centre de l ecran val 3 acceleration
if y>128 and y<room_height-128 ///fixe les bordures...
view_yview=lerp(view_yview,y-view_hview/2,acc) // camer lerp.... val1 xview, vale 2 centre de l ecran val 3 acceleration